<?php

    function employee_theme(){
        return array(
            // 'employee'=> array( 
            //     'variables'=> array(
            //         'items'=>[],
            //         'title'=>'',
            //     ),
                // 'template' => 'employee'
            // ),
            'custom_block' => [
                'variables' => [
                    'records' => [],
                ]
            ]
        );
    }

